config/routes.rb
Rails.application.routes.draw do
  # get 'gossips/:id', to: 'gossips#show_gossip', as: 'gossip'

  # get 'author/:id', to: 'gossips#gossip_author', as: 'author'

  get 'welcome/:user_entry', to: 'welcome#show_welcome', as: 'welcome'

  get 'team', to: 'static_pages#team'
  
  get 'contact', to: 'static_pages#contact'
  
  root 'static_pages#home'

  resources :gossips

  resources :authors

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :user
  validates :name, presence: true
  validates :zip_code, presence: true,
  uniqueness: true, 
  format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}\z/, message: "please enter a valid french zip code" }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commenteable, polymorphic: true
  has_many :likes, as: :likeable
  has_many :childs, class_name: "Comment",  as: :commenteable
  validates :content, presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :tags_by_gossips
  has_many :tags, through: :tags_by_gossips
  has_many :comments
  has_many :likes, as: :likeable
  has_many :comments, as: :commenteable
  validates :title, presence: true
  validates :content, presence: true, length: { minimum: 3, maximum: 14 }


end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true
end

app/models/multi_pm.rb
class MultiPm < ApplicationRecord
  belongs_to :user
  belongs_to :private_message
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"  
  has_many :multi_pms
  has_many :users, through: :multi_pms
  validates :content, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tags_by_potins
  has_many :gossips, through: :tags_by_gossips
  validates :title, presence: true
end

app/models/tag_by_gossip.rb
class TagByGossip < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :likes
  has_many :comments
  has_many :private_messages

  # has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  # has_many :received_messages, foreign_key: 'recipient_id', class_name: "MultiPm"
  # has_many :multi_pms
  # has_many :private_messages, through: :multi_pms
  # has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  
  def show
    @user = User.find(params[:id])
   end

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def show
    @gossips = Gossip.find(params[:id])
  end

   def new
    puts "*" * 60
    puts "on est dans le new gossip"
    puts params
    puts "*" * 60
   end

   def create
    puts "$" * 60
    puts "dans le Create ceci est le contenu de params :"
    puts params
    puts params[:content]
    puts params[:author]
    puts params[:title]
    puts "$" * 60

    @gossip = Gossip.new(
      'content' => params[:content],
      'title' => params[:title],
      'user_id' => "11" )

    if @gossip.save
    redirect_to root_path
    else
    render 'new'
    end

   end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def team
  end

  def contact
  end

  def home
    @gossips = Gossip.all
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show_welcome
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/views/authors/show.html.erb
<div class="jumbotron">
  <h4 class="display-4">Author details for <%= @user.first_name %> <%= @user.last_name %></h4></br>
  <p class="lead"><strong>Author first name: </strong></br><%= @user.first_name %></p>
  <p class="lead"><strong>Author last name: </strong></br><%= @user.last_name %></p>
  <p class="lead"><strong>Author age: </strong></br><%= @user.age %></p>
  <p class="lead"><strong>Description: </strong></br><%= @user.description %></p>
  <p class="lead"><strong>Email: </strong></br><%= @user.email %></p>
</div>

app/views/gossips/new.html.erb
<html>
  <body>

<p>Le 2ème form</p>
<%= form_tag url_for(action: 'create'), method: "post" do %>

<%= label_tag 'Title' %>
      <%= text_field_tag 'title', @gossip %>
      <br /> <br />

      <%= label_tag 'Content' %>
      <%= text_area_tag 'content', @gossip %>
      <br /> <br />

<%= submit_tag "Create Post" %>

<% end %>

 </body>
</html>

app/views/gossips/old_gossip_author.html.erb
<div class="jumbotron">
  <h4 class="display-4">Author details for <%= @user.first_name %> <%= @user.last_name %></h4></br>
  <p class="lead"><strong>Author first name: </strong></br><%= @user.first_name %></p>
  <p class="lead"><strong>Author last name: </strong></br><%= @user.last_name %></p>
  <p class="lead"><strong>Author age: </strong></br><%= @user.age %></p>
  <p class="lead"><strong>Description: </strong></br><%= @user.description %></p>
  <p class="lead"><strong>Email: </strong></br><%= @user.email %></p>
</div>

app/views/gossips/show.html.erb
<div class="jumbotron">
  <h4 class="display-4">Gossip n°<%= @gossips.id%></h4>
  <p class="lead"><strong>Author : </strong></br><%= link_to "#{@gossips.user.first_name} #{@gossips.user.last_name}", author_path(@gossips.user.id) %></p>
  <p class="lead"><strong>Title : </strong></br><%= @gossips.title.capitalize %></p>
  <p class="lead"><strong>Content : </strong></br><%= @gossips.content %></p>
  <p class="lead"><strong>Creation date : </strong></br><%= @gossips.created_at.strftime("%d-%m-%Y") %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://bootswatch.com/4/pulse/bootstrap.min.css">

  </head>

  <body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <%= link_to "The Gossip Project", root_path , class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">

      
      
      <li class="nav-item">
        <%= link_to "Team", team_path , class: "nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to "Contact", contact_path , class: "nav-link" %>
      </li>

    </ul>
  </div>
</nav>
<div  style="max-width: 90%; margin: 40px auto">

  <%= yield %>
</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  </body>
</html>

app/views/static_pages/contact.html.erb
<h1>Contact</h1></br>
<h3>Pour nous contacter : </h3></br>

<p>Vous pouvez nous appeler, nous envoyer un email ou un courrier ...</p>

<p><%= image_tag("Nous-Contacter.png", :alt => "cheval postal") %></p>

app/views/static_pages/home.html.erb
<p><%= link_to "CREATE NEW GOSSIP", new_gossip_path , class: "nav-link" %></P>

<h3>Bienvenue sur <span class="text-primary">The Gossip Project</span> !</h3>
<p>Voila la liste des gossips déjà publiés :</p>



<div class="row justify-content-around">
  <% @gossips.each do |gossip| %>
    <div class="card border-secondary bg-light mb-3 w-25 mx-5">
    <div class="card-body">
      <h4 class="card-title"><%= (gossip.title).capitalize %></h4>
      <h5 class="card-subtitle mb-2 text-muted"><%= gossip.user.first_name %> <%= gossip.user.last_name %></h5></br>
      <%= link_to "Voir le gossip", gossip_path(gossip.id), type: "button", class: "btn btn-outline-primary" %></br></br>
      <%= link_to "Voir la page de l'auteur", author_path(gossip.user.id), type: "button", class: "btn btn-outline-secondary" %>
    </div>
    </div>

  <% end %>
</div>

app/views/static_pages/team.html.erb
<h1>Team</h1></br>
<h3>Qui fait partie de la team?</h3></br>
<p>Et bien justement, il s'agit de nous, oui, de nous. Ca t'en bouche un coin non ? Héhé</p>
<p><%= image_tag("iconsport_vim_310517_78_35.jpg", :alt => "team rocket") %></p>

app/views/welcome/show_welcome.html.erb
<div class="alert alert-dismissible alert-success">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong>BIENVENUE <%= params[:user_entry] %> !</strong></br> Ici c'est notre super site de potins, il est chouette, non ?
</div>